- doi:10.1101/2023.06.28.546898
- doi:10.1101/2021.06.23.21259416
- id: url:http://ceur-ws.org/Vol-2976/paper-2.pdf
  title: An Open-Publishing Response to the COVID-19 Infodemic
  authors:
  - Halie M. Rando
  - Simina M. Boca
  - Lucy D'Agostino McGowan
  - Daniel S. Himmelstein
  - Michael P. Robson
  - Vincent Rubinetti
  - Ryan Velazquez
  - Casey S. Greene
  - Anthony Gitter
  publisher: Digital Infrastructures for Scholarly Content Objects 2021
  date: '2021-09-30'
  link: http://ceur-ws.org/Vol-2976/paper-2.pdf
