- id: doi:10.1093/jhered/esae022
  type: journal paper
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/jhered/PAP/10.1093_jhered_esae022/2/esae022_fig5.jpeg?Expires=1723205087&Signature=mh2K5Shh-1aChRpFUPq8dPl4ialuOAmtNKsM7XG945m-JwAUUszmS4h4GE0v-rxl2AyRgTLF33b3g78SzVtNpTIpcOPVbmKDa2WQBbtW9LHyhy76-c2DRfWqiTu6oRSuBSilJSVIADe7vLNXMmEOcDT5sa7pAUnYJTDn-3zMoVFtakNdZVdyU7-M6Bm-KcJO1cemNxk2602QfDnSWmyZyvCGjPcjiQK2Eqv83vdBADVlDgVkgJ83~Dno4tSCV3vSrznWuwe3g-izFviWP-sQB-JbbjqRIguAZbund7hYvV8-gNaUof9UcjrbGOQQSiN8iJ1lJakfd8zxruLpA4FvLA__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
      - domestication
      - foxes
      - wildlife
- id: doi:10.2460/javma.23.07.0372
  type: journal paper
  image: https://user-images.githubusercontent.com/8975841/250271905-4eed44ba-528a-4a61-a4ec-fa90d51e61f9.jpg
  tags:
      - reproducibility
      - genetics
      - dogs
      
- id: url:https://icbo-conference.github.io/icbo2022/papers/ICBO-2022_paper_1882.pdf
  type: conference paper
  image: https://user-images.githubusercontent.com/8975841/260512613-910f7bcd-2648-48db-8874-d37bca58c8f1.png
  title: Classifying animal breeds with the vertebrate breed ontology (VBO)
  authors:
      - Sabrina Toro
      - Nicolas Matentzoglu
      - Kathleen R. Mullen
      - Nicole Vasilevsky
      - Halie M. Rando
      - Melissa Haendel
      - Christopher J. Mungall
      - Zhi-Liang Hu
      - Gregoire Leroy
      - Imke Tammen
      - Frank W. Nicholas
  publisher: Proceedings of the International Conference on Biomedical Ontology 
  date: "2022-09-25"
  tags:
    - ontology
    - animals
    - domestication

- id: doi:10.1016/j.ebiom.2021.103722
  type: journal paper
  image: https://www.medrxiv.org/content/medrxiv/early/2021/06/29/2021.06.23.21259416/F1.large.jpg?width=800&height=600&carousel=1
  tags:
      - ontology
      - disease
      - humans

- id: url:http://ceur-ws.org/Vol-2976/paper-2.pdf
  type: conference paper
  image: https://user-images.githubusercontent.com/8975841/137757668-cf24b018-5539-4969-965f-305fee56b2d3.png
  title: An Open-Publishing Response to the COVID-19 Infodemic
  authors:
    - Halie M. Rando
    - Simina M. Boca
    - Lucy D'Agostino McGowan
    - Daniel S. Himmelstein
    - Michael P. Robson
    - Vincent Rubinetti
    - Ryan Velazquez
    - Casey S. Greene
    - Anthony Gitter
  publisher: Digital Infrastructures for Scholarly Content Objects 2021
  date: "2021-09-30"
  tags:
    - manubot
    - reproducibility
    - documents
- id: doi:10.1128/mSystems.00122-21
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/msystems.00095-21 
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/mSystems.00233-21
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.48550/ARXIV.2204.12598  
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/msystems.00927-22 
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1128/msystems.00928-22 
  image: https://greenelab.github.io/covid19-review/images/N000-overview.png
  tags:
      - manubot
      - COVID-19
- id: doi:10.1101/2021.03.20.21253896
  image: https://user-images.githubusercontent.com/8975841/112666874-013a3400-8e33-11eb-9be9-5c74f3e397ea.png
  type: preprint
  tags:
      - ontology
      - disease
      - humans
- id: doi:10.3390/genes10060409 
  image: images/thumbnails/sequencing_red_fox.png
  tags:
      - foxes
      - genomes
      - machine learning
- id: doi:10.3390/genes12010097
  image: images/thumbnails/Red_fox_ychromosome_genes10060409.png 
  tags:
      - foxes
      - genomes
      - wildlife
- id: doi:10.1111/age.12755
  image: images/thumbnails/Four_structural_variants.png 
  tags:
      - foxes
      - genomes
      - dogs
      - behavior
      - domestication
- id: doi:10.1038/s41559-018-0611-6
  image: images/thumbnails/red_fox_genome_assembly.png 
  tags:
      - foxes
      - genomes
      - behavior
      - domestication
- id: doi:10.3390/genes9060308
  image: images/thumbnails/red_fox_chromosomal_fragments.png 
  tags:
      - foxes
      - genomes
      - high-performance computing
- id: doi:10.1002/ece3.3583
  image: images/thumbnails/immunogenetic_assay.png
  tags:
      - foxes
      - genomes
      - wildlife
- id: doi:10.1093/jhered/esx066
  image: images/thumbnails/y_chromosome_markers.png
  tags: 
      - foxes
      - genomes
      - wildlife
